export type TripStatus =
  | "scheduled"
  | "in_progress"
  | "completed"
  | "cancelled";

export interface Trip {
  id: string;
  route: string;
  driver: string | null;
  vehicle: string | null;
  departureTime: Date;
  arrivalTime: Date;
  status: TripStatus;
  passengers: number;
  stops: string[];
  isAutoGenerated: boolean;
  scheduleId?: string;
}
