import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import Menu from "./components/menu";
import Navbar from "./components/navbar";
import styles from "@/styles/main.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="d-flex flex-column" style={{ height: "100vh" }}>
        <Navbar />
        <div className="flex-grow-1" style={{ marginLeft: '280px', marginTop: '60px' }}>
          <Menu />
          <main className={`main ${styles.main}`}>
            <h3 className="text-center">Hello World!</h3>
          </main>
        </div>
      </div>
    </>
  );
}
