import { Trip } from "@/types/trip";

export const mockTrips: Trip[] = [
  {
    id: "1",
    route: "Centro - Universidade",
    driver: "João Silva",
    vehicle: "BUS-2024",
    departureTime: new Date("2024-03-20T08:00:00"),
    arrivalTime: new Date("2024-03-20T09:30:00"),
    status: "scheduled",
    passengers: 0,
    stops: ["Terminal Central", "Shopping", "Campus Universitário"],
    isAutoGenerated: true,
    scheduleId: "1",
  },
  {
    id: "2",
    route: "Centro - Shopping",
    driver: "Maria Santos",
    vehicle: "BUS-2025",
    departureTime: new Date("2024-03-20T09:00:00"),
    arrivalTime: new Date("2024-03-20T10:30:00"),
    status: "scheduled",
    passengers: 0,
    stops: ["Terminal Central", "Praça Central", "Shopping"],
    isAutoGenerated: true,
    scheduleId: "2",
  },
];
